version: '3.2'

volumes:
  multitenantdata:
    driver: local

services:
  db:
    image: postgres:11
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    volumes:
      - multitenantdata:/var/lib/postgresql/data/pgdata

  tenant:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3005:3000'
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      WEBPACKER_DEV_SERVER_HOST: webpack
    stdin_open: true
    tty: true
    command: bash -c "rake db:create && rake db:migrate && bin/rails server -b 0.0.0.0"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  